---
# =========================
# Baseline admin user
# =========================
admin_user: nafuradmin
admin_user_sudo_nopasswd: true

admin_user_ssh_keys:
  - "{{ lookup('file', 'assets/admin_user.pub') }}"

# ========================
# Default connection behavior
# ========================
# Normal Linux hosts use the admin user and sudo
# Override in host_vars for special cases like Proxmox boostrap or OPNsense
ansible_user: "{{ admin_user }}"
ansible_become: true


# =========================
# Proxmox defaults
# =========================
is_proxmox_node: false
proxmox_auth_realm: pam
proxmox_acl_path: /
proxmox_role: Administrator

# =========================
# step-ca / duration Enforcement
# =========================
step_ca_x509_default_dur: "720h"
step_ca_x509_min_dur: "720h"
step_ca_x509_max_dur: "1080h"

# =========================
# step-ca / internal PKI defaults
step_ca_url: "https://ca.lan.basedeep.net/acme/acme/directory"
step_ca_root_cert_local_src: "assets/lan-basedeep-root-ca.crt"
step_ca_root_cert_filename: "lan-basedeep-root-ca.crt"

# acme.sh / cert staging location
step_ca_cert_base_dir: "/opt/internal-pki"
step_ca_acme_ca_bundle_path: "/root/root_ca.crt"

# Role toggles
step_ca_issue_enabled: true
pve_tls_enabled: true
