# Auth Credentials
admin_user_ssh_keys:
  - "{{ lookup('file', playbook_dir + '/assets/admin_user.pub') }}"

# Internal PKI CA Details
step_ca_issue_enabled: false
step_ca_url: "https://ca1.basedeep.net"
step_ca_port: 53
step_download_url: "https://{{ step_ca_url }}:{{ step_ca_port }}/roots.pem"
step_ca_fingerprint: "bcc772e5130071641954685c5e63867e2d109a627e5448011a30e294d2be80d5"
step_ca_acme_directory: "{{ step_ca_url }}/acme/acme/directory"
step_ca_cert_base_dir: "/etc/pki/staged"
acme_home: "/root/.acme.sh"
acme_ca_bundle:
  - "{{ lookup('file', playbook_dir + '/assets/basedeep-root.crt') }}"
acme_sh_path: "/root/.acme.sh/acme.sh"

step_root_ca: 'vault/'
step_intermediate_ca: 'vault/'

# Custom module add_on features
naming_enforce: false

# Conditionals
skip_reboot_hosts:
  - prox.basedeep.net
  - edge.basedeep.net
  - localhost
