[controllers]
localhost ansible_host=127.0.0.1

[step_ca]
ca1.basedeep.net ansible_host=10.0.10.20

[npm_hosts]
npm-svr.basedeep.net ansible_host=10.0.10.4
twin1.basedeep.net ansible_host=10.0.20.8
twin2.basedeep.net ansible_host=10.0.20.9
ns1.basedeep.net ansible_host=10.0.10.7
ns2.basedeep.net ansible_host=10.0.10.5

[firewalls]
edge.basedeep.net ansible_host=10.0.10.1

[proxmox]
prox.basedeep.net ansible_host=10.0.10.15
