[step_ca]
ca.lan.basedeep.net ansible_host=10.0.10.20

[npm_hosts]
npmsvr.lan.basedeep.net ansible_host=10.0.10.4
techns01.lan.basedeep.net ansible_host=10.0.10.5
cntl01.lan.basedeep.net ansible_host=10.0.10.15

[firewalls]
edge.lan.basedeep.net ansible_host=10.0.10.1

[proxmox]
prox.lan.basedeep.net ansible_host=10.0.10.15
