---
- name: Run & validate the step_ca_provisioner task
  hosts: ca.lan.basedeep.net
  roles:
    - step_ca_provisioner

- name: Baseline and CA trust
  hosts: all
  become: true
  gather_facts: true
  roles:
    - base
    - step_ca_trust
    - step_ca_issue

- name: Issue and install Proxmox certificate
  hosts: proxmox
  become: true
  gather_facts: true
  roles:
    - pve_tls
