---
- name: Download the current Step-CA root certificate
  ansible.builtin.get_url:
    url: "https://{{ step_ca_url }}:{{ step_ca_port }}/roots.pem"
    dest: /usr/local/share/ca-certificates/step_ca_root.crt
    mode: '0644'
    validate_certs: false
  register: download_cert

- name: Update system CA trust store
  ansible.builtin.command: update-ca-certificates
  when: download_cert.changed

- name: Bootstrap the step CLI tool for the current user
  ansible.builtin.command: >
    step ca bootstrap
    --ca-url "https://{{ step_ca_url }}:{{ step_ca_port }}"
    --fingerprint "{{ step_ca_fingerprint }}"
    --force
  become: false
  changed_when: true
