---
- name: refresh debian ca trust
  ansible.builtin.command: update-ca-certificates --fresh
  when: ansible_os_family == "Debian"
  changed_when: true

- name: refresh redhat ca trust
  ansible.builtin.command: update-ca-trust extract
  when: ansible_os_family == "RedHat"
  changed_when: true
