---
- name: "Copy staged cert to Proxmox temporary location"
  copy:
    src: "{{ staged_cert_fullchain }}"
    dest: "/var/tmp/{{ inventory_hostname }}.crt"
    owner: root
    group: root
    mode: '0644'

- name: "Copy staged key to Proxmox temporary location"
  copy:
    src: "{{ staged_cert_key }}"
    dest: "/var/tmp/{{ inventory_hostname }}.key"
    owner: root
    group: root
    mode: '0600'

- name: "Overwrite Proxmox pve-ssl.pem using cp to avoid pmxcfs tempfile issues"
  command: cp /var/tmp/{{ inventory_hostname }}.crt /etc/pve/local/pve-ssl.pem
  become: true

- name: "Overwrite Proxmox pve-ssl.key using cp to avoid pmxcfs tempfile issues"
  command: cp /var/tmp/{{ inventory_hostname }}.key /etc/pve/local/pve-ssl.key
  become: true

- name: "Set permissions on Proxmox cert and key"
  command: chown root:www-data /etc/pve/local/pve-ssl.pem && chmod 0640 /etc/pve/local/pve-ssl.pem && chown root:www-data /etc/pve/local/pve-ssl.key && chmod 0640 /etc/pve/local/pve-ssl.key
  become: true

- name: "Restart Proxmox proxy"
  systemd:
    name: pveproxy
    state: restarted
  become: true

