---
- name: Run OS updates
  ansible.builtin.import_tasks: updates.yml

- name: Configure admin user
  ansible.builtin.import_tasks: admin_user.yml

- name: Configure Proxmox access for admin user
  ansible.builtin.import_tasks: proxmox_user.yml

